param(
    [switch]$Headless
)

$ErrorActionPreference = 'Stop'
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $RepoRoot

$VenvPython = Join-Path $RepoRoot '.venv-win\Scripts\python.exe'
if (-not (Test-Path $VenvPython)) {
    throw 'Run setup-and-unit-test.ps1 first. .venv-win was not found.'
}

# Keep Korean/₩ diagnostics readable in Windows console.
$env:PYTHONUTF8 = '1'
$env:PYTHONIOENCODING = 'utf-8'
try { chcp 65001 > $null } catch { }

$env:BROWSER_HEADLESS = if ($Headless) { 'true' } else { 'false' }
$env:BROWSER_TIMEOUT_MS = '60000'
$env:BROWSER_DEBUG_DIR = (Join-Path $RepoRoot 'artifacts\google-ui-win')
$env:BROWSER_PROFILE_DIR = (Join-Path $RepoRoot 'artifacts\google-profile-win')
$env:BROWSER_KEEP_OPEN_SECONDS = if ($Headless) { '0' } else { '6' }
$env:GOOGLE_UI_TRANSIENT_WAIT_MS = '5000'

# Acceptance-only speed-up: reuse the canonical URL previously generated by the
# Google Flights UI for this fixed CJJ/TPE/date scenario. Production search still
# has to generate dynamic URLs from user criteria.
$env:GOOGLE_UI_SEARCH_URL = 'https://www.google.com/travel/flights/search?tfs=CBwQAhoeEgoyMDI2LTA5LTE4agcIARIDQ0pKcgcIARIDVFBFGh4SCjIwMjYtMDktMjBqBwgBEgNUUEVyBwgBEgNDSkpAAUgBcAGCAQsI____________AZgBAQ&hl=en&gl=kr&curr=KRW'

# Do not use the user's personal Edge/Chrome profile.
Remove-Item Env:BROWSER_CHANNEL -ErrorAction SilentlyContinue

Write-Host 'Google Flights transient-price acceptance probe'
Write-Host '  CJJ -> TPE'
Write-Host '  2026-09-18 ~ 2026-09-20'
Write-Host '  1 adult / Economy / KRW'
Write-Host '  canonical generated acceptance URL reuse: YES'
Write-Host '  initial form-entry stage skipped for faster testing'
Write-Host '  MutationObserver before Google page scripts: YES'
Write-Host '  capture price before Price unavailable replacement: YES'
Write-Host '  flight-row scope required: YES'
Write-Host '  body-wide price fallback: NO'
Write-Host '  observed price != booking verified price'
Write-Host "  transient wait: $($env:GOOGLE_UI_TRANSIENT_WAIT_MS) ms"
Write-Host "  headless: $($env:BROWSER_HEADLESS)"
Write-Host ''

& $VenvPython 'scripts\google_transient_price_probe.py'
if ($LASTEXITCODE -ne 0) {
    throw "Google transient-price probe failed with exit code $LASTEXITCODE. Check artifacts\google-ui-win."
}

Write-Host ''
Write-Host 'Probe complete.'
Write-Host 'Paste the transient candidate list and SUMMARY output into the next ChatGPT chat.'
