param(
    [switch]$Headless
)

$ErrorActionPreference = 'Stop'
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $RepoRoot

$VenvPython = Join-Path $RepoRoot '.venv-win\Scripts\python.exe'
if (-not (Test-Path $VenvPython)) {
    throw 'Run setup-and-unit-test.ps1 first. .venv-win was not found.'
}

# Keep Korean/₩ diagnostics readable in Windows console.
$env:PYTHONUTF8 = '1'
$env:PYTHONIOENCODING = 'utf-8'
try { chcp 65001 > $null } catch { }

$env:BROWSER_HEADLESS = if ($Headless) { 'true' } else { 'false' }
$env:BROWSER_TIMEOUT_MS = '60000'
$env:BROWSER_DEBUG_DIR = (Join-Path $RepoRoot 'artifacts\google-ui-win')
$env:BROWSER_PROFILE_DIR = (Join-Path $RepoRoot 'artifacts\google-profile-win')
$env:BROWSER_KEEP_OPEN_SECONDS = if ($Headless) { '0' } else { '8' }
$env:GOOGLE_UI_SELECTION_WAIT_MS = '20000'
$env:GOOGLE_UI_BOOKING_WAIT_MS = '15000'

# Acceptance-only speed-up: reuse the canonical URL previously generated by the
# Google Flights UI for this fixed CJJ/TPE/date scenario. Production search still
# has to generate dynamic URLs from user criteria.
$env:GOOGLE_UI_SEARCH_URL = 'https://www.google.com/travel/flights/search?tfs=CBwQAhoeEgoyMDI2LTA5LTE4agcIARIDQ0pKcgcIARIDVFBFGh4SCjIwMjYtMDktMjBqBwgBEgNUUEVyBwgBEgNDSkpAAUgBcAGCAQsI____________AZgBAQ&hl=en&gl=kr&curr=KRW'

# Do not use the user's personal Edge/Chrome profile.
Remove-Item Env:BROWSER_CHANNEL -ErrorAction SilentlyContinue

Write-Host 'Google Flights source-anchored pointer selection + Booking options probe'
Write-Host '  CJJ -> TPE -> CJJ'
Write-Host '  2026-09-18 ~ 2026-09-20'
Write-Host '  1 adult / Economy / KRW'
Write-Host '  canonical acceptance URL reuse: YES'
Write-Host '  direct-price element only: YES'
Write-Host '  broad results container rejected: YES'
Write-Host '  DOM element.click fallback: NO'
Write-Host '  real Playwright mouse click: YES'
Write-Host '  transient lowest departure auto-click: YES'
Write-Host '  transient lowest return auto-click: YES'
Write-Host '  Booking CTA-scoped price inspection: YES'
Write-Host '  external seller checkout verification: NO'
Write-Host '  body-wide price fallback: NO'
Write-Host "  selection wait: $($env:GOOGLE_UI_SELECTION_WAIT_MS) ms"
Write-Host "  booking wait: $($env:GOOGLE_UI_BOOKING_WAIT_MS) ms"
Write-Host "  headless: $($env:BROWSER_HEADLESS)"
Write-Host ''

& $VenvPython 'scripts\google_booking_pointer_probe.py'
if ($LASTEXITCODE -ne 0) {
    throw "Google UI pointer booking probe failed with exit code $LASTEXITCODE. Check artifacts\google-ui-win."
}

Write-Host ''
Write-Host 'Probe complete.'
Write-Host 'Paste the departure/return/Booking output and SUMMARY into the next ChatGPT chat.'
